### ISSUE TITLE
BuildServer update script

### ISSUE THREAD

**Issue by TheChymera** [IBT-FMI/NeuroGentooProject#9]
The cron jobs didn't seem to be executing, and it seems there's something wrong with the command. I couldn't exactly figure out what `pushd` is supposed to do, so I'm not sure whether something is obviously amiss here. Is it supposed to dynamically set the cwd.

```
builder ~ # cat /etc/cron.weekly/buildserver_update.sh 
#!/bin/bash

set -e

ROOT_DIR="$(dirname "$(realpath "$0")")/../"
ROOT_DIR="${1:-$ROOT_DIR}"

pushd "${ROOT_DIR}"
./exec.sh stemgentoo update
for file in roots/*/.gentoo/
do
        ./exec.sh "$file" update
done
popd
builder ~ # ls -lah /etc/cron.weekly/buildserver_update.sh 
-rwxr-xr-x 1 root root 217 Dec 24 17:04 /etc/cron.weekly/buildserver_update.sh
builder ~ # cd /etc/cron.weekly/
builder /etc/cron.weekly # ./buildserver_update.sh 
/etc /etc/cron.weekly
./buildserver_update.sh: line 9: ./exec.sh: No such file or directory
```

Also, any idea if the cron jobs are logged anywhere? I can't find anything in either `/var/log/messages` or  ` /var/log/cron.log`.

**Comment by Doeme** [comment]
Yeah, the cronjob-script makes certain assumptions about where the images are stored. If you link instead of copying it, it will figure that out and use `$REAL_PATH/../exec.sh $REAL_PATH/../roots/*/*`.

This requires that ./exec.sh and ./roots/ are in the same directory, which otherwise does not necessarily have to be the case.
This can be solved by actually installing the BuildServer to /usr/bin/, which is done by the ebuild inside .gentoo, but the cronjob.sh then has to be adapted (it is only an example anyways) to use the global buildserver script.

**Comment by TheChymera** [comment]
solved in [gebuilder](https://github.com/IBT-FMI/gebuilder).
